apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: api
  labels:
    app: makeauto-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: makeauto-api
  template:
    metadata:
      labels:
        app: makeauto-api
    spec:
      serviceAccountName: api-sa
      containers:
        - name: api
          image: "us-central1-docker.pkg.dev/iot-k8s-petor/makeauto-repo/makeauto-api:latest"
          imagePullPolicy: Always
          env:
            # ----- PROJECT -----
            - name: PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: makeauto-config
                  key: PROJECT_ID

            # ----- CONFIGMAP -----
            - name: PUBSUB_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: makeauto-config
                  key: PUBSUB_TOPIC

            - name: SQL_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: makeauto-config
                  key: SQL_DB_NAME

            # ----- SECRETS -----
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  name: makeauto-secrets
                  key: SQL_USER

            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: makeauto-secrets
                  key: SQL_PASSWORD

            - name: SQL_INSTANCE_CONNECTION_NAME
              valueFrom:
                secretKeyRef:
                  name: makeauto-secrets
                  key: SQL_INSTANCE_CONNECTION_NAME

            # ----- VARIABLES DE RUNTIME -----
            - name: PORT
              value: "8080"

          ports:
            - containerPort: 8080

          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
