apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: api
  labels:
    app: makeauto-api
spec:
  type: ClusterIP
  selector:
    app: makeauto-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
