apiVersion: v1
kind: Service
metadata:
  name: processor-service
  namespace: processor
  labels:
    app: makeauto-processor
spec:
  type: ClusterIP
  selector:
    app: makeauto-processor
  ports:
    - name: dummy
      port: 80
      targetPort: 8080
