apiVersion: v1
kind: Secret
metadata:
  name: makeauto-secrets
  namespace: api
type: Opaque
data:
  SQL_USER: "aW90c2VydmljZQ=="   # ok
  SQL_PASSWORD: "TWlQYXNzd29yZEZ1ZXJ0ZTEyMyE="
  SQL_INSTANCE_CONNECTION_NAME: "aW90LWs4cy1wZXRvcjp1cy1jZW50cmFsMTptYWtlYXV0by1zcWw="
---
apiVersion: v1
kind: Secret
metadata:
  name: makeauto-secrets
  namespace: processor
type: Opaque
data:
  SQL_USER: "aW90c2VydmljZQ=="   # ok
  SQL_PASSWORD: "TWlQYXNzd29yZEZ1ZXJ0ZTEyMyE="
  SQL_INSTANCE_CONNECTION_NAME: "aW90LWs4cy1wZXRvcjp1cy1jZW50cmFsMTptYWtlYXV0by1zcWw="
---
apiVersion: v1
kind: Secret
metadata:
  name: makeauto-secrets
  namespace: dashboard
type: Opaque
data:
  SQL_USER: "aW90c2VydmljZQ=="   # ok
  SQL_PASSWORD: "TWlQYXNzd29yZEZ1ZXJ0ZTEyMyE="
  SQL_INSTANCE_CONNECTION_NAME: "aW90LWs4cy1wZXRvcjp1cy1jZW50cmFsMTptYWtlYXV0by1zcWw="
