apiVersion: v1
kind: Secret
metadata:
  name: makeauto-secrets
  namespace: api
type: Opaque
data:
  SQL_USER: "YXBwdXNlcg=="
  SQL_PASSWORD: "TWlQYXNzd29yZGVGdWVydGUxMjMh"
  SQL_INSTANCE_CONNECTION_NAME: "aW90LWs4cy1wZXRvcjp1cy1jZW50cmFsMTptYWtlYXV0by1zcWw="
---
apiVersion: v1
kind: Secret
metadata:
  name: makeauto-secrets
  namespace: processor
type: Opaque
data:
  SQL_USER: "YXBwdXNlcg=="
  SQL_PASSWORD: "TWlQYXNzd29yZGVGdWVydGUxMjMh"
  SQL_INSTANCE_CONNECTION_NAME: "aW90LWs4cy1wZXRvcjp1cy1jZW50cmFsMTptYWtlYXV0by1zcWw="
---
apiVersion: v1
kind: Secret
metadata:
  name: makeauto-secrets
  namespace: dashboard
type: Opaque
data:
  SQL_USER: "YXBwdXNlcg=="
  SQL_PASSWORD: "TWlQYXNzd29yZGVGdWVydGUxMjMh"
  SQL_INSTANCE_CONNECTION_NAME: "aW90LWs4cy1wZXRvcjp1cy1jZW50cmFsMTptYWtlYXV0by1zcWw="
