apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-sa
  namespace: api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: processor-sa
  namespace: processor
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard-sa
  namespace: dashboard
