apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-sa
  namespace: api
  annotations:
    iam.gke.io/gcp-service-account: makeauto-api-sa@iot-k8s-petor.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: processor-sa
  namespace: processor
  annotations:
    iam.gke.io/gcp-service-account: makeauto-processor-sa@iot-k8s-petor.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard-sa
  namespace: dashboard
  annotations:
    iam.gke.io/gcp-service-account: makeauto-dashboard-sa@iot-k8s-petor.iam.gserviceaccount.com
